import { FormEvent, useEffect, useState } from 'react'
import { useAuth } from '../../app/AuthProvider'
import { createCatalogItem, listManagedCatalog, listTeams, updateCatalogItem } from '../../api/admin'
import type { ServiceCatalogItem, Team } from '../../types/workflow'

const emptyForm = { service_key: '', name: '', description: '', desk_id: 'ops' as const, team_id: '', keywords: '', default_category: '', is_active: true }

export function AdminCatalogPage(): JSX.Element {
  const auth = useAuth(); const [items, setItems] = useState<ServiceCatalogItem[]>([]); const [teams, setTeams] = useState<Team[]>([]); const [form, setForm] = useState(emptyForm); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  const load = async () => { if (!auth.token) return; try { const [catalog, teamItems] = await Promise.all([listManagedCatalog(auth.token), listTeams(auth.token)]); setItems(catalog); setTeams(teamItems) } catch (caught) { setError(caught instanceof Error ? caught.message : '加载失败') } }
  useEffect(() => { void load() }, [auth.token])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!auth.token) return; setBusy(true); try { await createCatalogItem({ service_key: form.service_key, name: form.name, description: form.description, desk_id: form.desk_id, team_id: form.team_id || null, keywords: form.keywords.split(',').map((value) => value.trim()).filter(Boolean), default_category: form.default_category || null, is_active: true }, auth.token); setForm(emptyForm); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : '创建失败') } finally { setBusy(false) } }
  const toggle = async (item: ServiceCatalogItem) => { if (!auth.token) return; setBusy(true); try { await updateCatalogItem(item.id, { is_active: !item.is_active }, auth.token); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : '更新失败') } finally { setBusy(false) } }
  return <div className="page-stack"><header className="page-header"><div><span className="eyebrow">管理控制台</span><h1>服务目录</h1><p>维护服务归属、匹配关键词和默认分类。</p></div><div className="page-stat"><strong>{items.filter((item) => item.is_active).length}</strong><span>启用服务</span></div></header>{error && <div className="error-banner">{error}</div>}<form className="surface inline-create-form" onSubmit={submit}><h2>新增服务</h2><div className="form-grid admin-form-grid"><label><span>服务标识</span><input aria-label="服务标识" pattern="[A-Za-z0-9_.-]+" value={form.service_key} onChange={(e) => setForm({ ...form, service_key: e.target.value })} /></label><label><span>服务名称</span><input aria-label="服务名称" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span>服务台</span><select value={form.desk_id} onChange={(e) => setForm({ ...form, desk_id: e.target.value as 'ops' })}><option value="ops">IT 运维</option><option value="support">内部支持</option></select></label><label><span>负责团队</span><select value={form.team_id} onChange={(e) => setForm({ ...form, team_id: e.target.value })}><option value="">未分配</option>{teams.filter((team) => team.is_active).map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label><span>默认分类</span><input value={form.default_category} onChange={(e) => setForm({ ...form, default_category: e.target.value })} /></label><label><span>关键词</span><input aria-label="服务关键词" value={form.keywords} onChange={(e) => setForm({ ...form, keywords: e.target.value })} placeholder="逗号分隔" /></label><label className="wide-field"><span>说明</span><input value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><button disabled={busy || !form.service_key || !form.name}>新增</button></div></form><section className="data-table"><div className="data-row catalog-row data-head"><span>服务</span><span>服务台</span><span>团队</span><span>关键词</span><span>状态</span><span>操作</span></div>{items.map((item) => <div className="data-row catalog-row" key={item.id}><span><strong>{item.name}</strong><small>{item.service_key}</small></span><span>{item.desk_id === 'ops' ? 'IT 运维' : '内部支持'}</span><span>{teams.find((team) => team.id === item.team_id)?.name ?? '未分配'}</span><span>{item.keywords.join('、') || '无'}</span><span><span className={item.is_active ? 'state-active' : 'state-inactive'}>{item.is_active ? '启用' : '停用'}</span></span><span><button className="button-quiet" disabled={busy} onClick={() => void toggle(item)}>{item.is_active ? '停用' : '启用'}</button></span></div>)}</section></div>
}
