import { FormEvent, useEffect, useState } from 'react'
import { Save } from 'lucide-react'
import { useAuth } from '../../app/AuthProvider'
import { createSlaPolicy, listSlaPolicies, updateSlaPolicy } from '../../api/admin'
import type { SlaPolicy } from '../../types/workflow'

export function AdminSlaPage(): JSX.Element {
  const auth = useAuth(); const [items, setItems] = useState<SlaPolicy[]>([]); const [form, setForm] = useState({ name: '', priority: 'P3' as SlaPolicy['priority'], response_minutes: 240, resolution_minutes: 1440, is_active: true }); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  const load = async () => { if (auth.token) try { setItems(await listSlaPolicies(auth.token)) } catch (caught) { setError(caught instanceof Error ? caught.message : '加载失败') } }
  useEffect(() => { void load() }, [auth.token])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!auth.token) return; setBusy(true); try { await createSlaPolicy(form, auth.token); setForm({ ...form, name: '' }); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : '创建失败') } finally { setBusy(false) } }
  const save = async (item: SlaPolicy) => { if (!auth.token) return; setBusy(true); try { await updateSlaPolicy(item.id, { name: item.name, response_minutes: item.response_minutes, resolution_minutes: item.resolution_minutes, is_active: item.is_active }, auth.token); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : '保存失败') } finally { setBusy(false) } }
  const updateLocal = (id: string, values: Partial<SlaPolicy>) => setItems((current) => current.map((item) => item.id === id ? { ...item, ...values } : item))
  return <div className="page-stack"><header className="page-header"><div><span className="eyebrow">管理控制台</span><h1>SLA 策略</h1><p>时限按自然时间计算，修改仅影响之后创建或重新分诊的工单。</p></div></header>{error && <div className="error-banner">{error}</div>}<form className="surface inline-create-form" onSubmit={submit}><h2>新增策略</h2><div className="form-grid admin-form-grid"><label><span>名称</span><input aria-label="SLA 名称" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span>优先级</span><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as SlaPolicy['priority'] })}><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select></label><label><span>响应分钟</span><input type="number" min={1} value={form.response_minutes} onChange={(e) => setForm({ ...form, response_minutes: Number(e.target.value) })} /></label><label><span>解决分钟</span><input type="number" min={1} value={form.resolution_minutes} onChange={(e) => setForm({ ...form, resolution_minutes: Number(e.target.value) })} /></label><button disabled={busy || !form.name}>新增</button></div></form><section className="sla-grid">{items.map((item) => <article className="surface sla-policy" key={item.id}><div className="sla-policy-title"><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><label className="switch-label"><input type="checkbox" checked={item.is_active} onChange={(e) => updateLocal(item.id, { is_active: e.target.checked })} />启用</label></div><label><span>名称</span><input value={item.name} onChange={(e) => updateLocal(item.id, { name: e.target.value })} /></label><div className="form-grid two-columns"><label><span>首次响应（分钟）</span><input type="number" min={1} value={item.response_minutes} onChange={(e) => updateLocal(item.id, { response_minutes: Number(e.target.value) })} /></label><label><span>解决（分钟）</span><input type="number" min={1} value={item.resolution_minutes} onChange={(e) => updateLocal(item.id, { resolution_minutes: Number(e.target.value) })} /></label></div><button className="button-secondary" disabled={busy} onClick={() => void save(item)}><Save size={16} />保存</button></article>)}</section></div>
}
